version: "3.7"
services:
  controle-db:
    image: postgres
    container_name: controle-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: controle
